### ISSUE TITLE
Сокращение длинных названий

### ISSUE THREAD

**Issue by KOTOKOPOLb** [FozerG/WinYandexMusicRPC#7]
Если длинна трека слишком большая - приложение крашится.
Можно сделать так, чтобы название трека сокращалось и в конце добавлялось многоточие...

Изначально просто хотел сообщить о небольшом баге:
```
Yandex Music API v2.1.1, Copyright (C) 2019-2023 Ilya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

[WinYandexMusicRPC] -> Now listening to Vivaldi String Orchestra, Julius Frederick Rinaldi, Антонио Вивальди - The Four Seasons, Concerto for Violin, Strings and Continuo in F Minor, No. 4, Op. 8, RV 297, "L' Inverno" (Winter): I. Allegro Non Molto
[WinYandexMusicRPC] -> Changed track to Vivaldi String Orchestra, Julius Frederick Rinaldi, Антонио Вивальди - The Four Seasons, Concerto for Violin, Strings and Continuo in F Minor, No. 4, Op. 8, RV 297, "L' Inverno" (Winter): I. Allegro Non Molto
Traceback (most recent call last):
  File "main.py", line 189, in <module>
  File "main.py", line 85, in start
  File "pypresence\presence.py", line 34, in update
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "pypresence\baseclient.py", line 88, in read_output
pypresence.exceptions.ServerError: Child "activity" fails because child "details" fails because "details" length must be less than or equal to 128 characters long
[964] Failed to execute script 'main' due to unhandled exception!
```

**Comment by FozerG** [comment]
Спасибо! Исправлено в [новой версии](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.5) 💕
